on: push
jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - run: whoami

      - name: Run a container that outputs to foo/output-file and puts nasty permissions on foo
        uses: ./

      - name: Print permissions for all files
        run: ls -alFR || true

      # Fails to git clean the foo folder, tries to rm -rf the checkout and then fails
      - uses: actions/checkout@v2
